services:
  - type: web
    name: schedule-bot
    runtime: python
    buildCommand: ""
    startCommand: python app/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
